INSERT INTO service (libelle) VALUES ('RH') ON CONFLICT DO NOTHING;
INSERT INTO service (libelle) VALUES ('INFORMATIQUE') ON CONFLICT DO NOTHING;
INSERT INTO service (libelle) VALUES ('MANAGEMENT') ON CONFLICT DO NOTHING;
